spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=true
    username: root
    password: 123456
logging:
  level: debug
#?useUnicode=true&characterEncoding=utf-8
